version: "3.7"

services:
    postgres:
        image: postgis/postgis:12-master
        container_name: "todo-api-db"
        ports:
            - "5444:5432"
        environment: 
            - "POSTGRES_DB=todo"
            - "POSTGRES_USER=todo_user"
            - "POSTGRES_PASSWORD=todopass"